config/routes.rb
Rails.application.routes.draw do
 
  resources :decuments
  resources :home
  post 'home/search'
    root to: "home#index"
  devise_for :users#, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
    devise_scope :user do
      get 'logout' => 'devise/sessions#destroy'
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EduHunt1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand" href="#">Home</a> -->
                <%= link_to 'Home',home_index_path, :class=>"navbar-brand"%>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                     <% if user_signed_in? %>
                    <li>
                        <!-- <a href="#about">Decuments</a> -->
                        <%= link_to 'Decuments',decuments_path%>
                    </li>
                    <%end%>
                    <li>
                        <a href="#services">Services</a>
                    </li>                   
                    <% if user_signed_in? %>
                    <li style="float:right;">
                        <!-- <a href="#contact">Contact</a> -->
                        <%= link_to 'Log Out', logout_path%>
                    </li>
                    <%else%>
                     <li>
                        <!-- <a href="#contact">Contact</a> -->
                        <%= link_to 'Log In', user_session_path%>
                        <%#= link_to 'Sing Up', new_user_registration_path%>
                    </li>
                    <li>
                       <%= link_to 'Sing Up', new_user_registration_path%>
                    </li>
                    <%end%>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<%= yield %>
<footer class="footer">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

</body>
</html>